// Request/response types from specs/design/components/payments-api/openapi.yaml,
// generated by `bal openapi --mode service` and moved out of the service file.
// The three inline request-body schemas were renamed from the tool's
// auto-generated `<path>_<verb>_body` names to ordinary two-word identifiers.

import ballerina/http;

public type ResolvePayoutRequest record {
    string resolutionNotes;
};

public type ResolveDisputeRequest record {
    string resolutionNotes;
};

public type RejectMerchantRequest record {
    string reason;
};

public type PaymentLinkInput record {
    int amount;
    string currency;
    string? expiresAt?;
};

public type MerchantOk record {|
    *http:Ok;
    Merchant body;
|};

public type PayoutInput record {
    int amount;
    "bank"|"mobile-wallet" destinationType;
    string bankAccountNumber?;
    string bankCode?;
    string mobileWalletNumber?;
};

public type PaymentLinkPage record {
    int count;
    string? next?;
    string? previous?;
    PaymentLink[] data;
};

public type DisputePage record {
    int count;
    string? next?;
    string? previous?;
    Dispute[] data;
};

public type Merchant record {
    string id;
    string businessName;
    string ownerName;
    string country;
    string currency;
    string contactEmail?;
    string contactPhone?;
    "pending"|"approved"|"rejected" kycStatus;
    # running balance in minor currency units
    int balance;
};

public type PaymentLink record {
    string id;
    string merchantId;
    int amount;
    string currency;
    "pending"|"paid"|"expired" status;
    string qrCodeUrl;
    string createdAt;
    string? expiresAt?;
};

public type Payout record {
    string id;
    string merchantId;
    int amount;
    string currency;
    "bank"|"mobile-wallet" destinationType;
    "pending"|"paid"|"failed" status;
    string? externalPayoutId?;
    string createdAt;
};

public type DisputeOk record {|
    *http:Ok;
    Dispute body;
|};

public type MerchantPage record {
    int count;
    string? next?;
    string? previous?;
    Merchant[] data;
};

public type PayoutOk record {|
    *http:Ok;
    Payout body;
|};

public type PayoutPage record {
    int count;
    string? next?;
    string? previous?;
    Payout[] data;
};

public type Error record {
    # HTTP or application error code
    int code;
    # short human-readable label
    string message;
    # detailed explanation
    string description?;
    # URI to documentation
    string moreInfo?;
};

public type ErrorBadRequest record {|
    *http:BadRequest;
    Error body;
|};

public type PaymentLinkPublic record {
    string id;
    string merchantName;
    int amount;
    string currency;
    "pending"|"paid"|"expired" status;
};

public type ErrorNotFound record {|
    *http:NotFound;
    Error body;
|};

public type Transaction record {
    string id;
    string merchantId;
    string paymentLinkId;
    "mobile-money"|"card" method;
    int amount;
    string currency;
    "pending"|"completed"|"failed" status;
    string? externalPaymentId?;
    string createdAt;
};

public type Refund record {
    string id;
    string transactionId;
    int amount;
    "pending"|"completed"|"failed" status;
    string createdAt;
};

public type PaymentRequest record {
    "mobile-money"|"card" method;
    # required for mobile-money
    string payerPhone?;
    # required for card
    string payerCardToken?;
};

public type TransactionPage record {
    int count;
    string? next?;
    string? previous?;
    Transaction[] data;
};

public type MerchantInput record {
    string businessName;
    string ownerName;
    string country;
    string currency;
    string contactEmail;
    string contactPhone;
};

public type Dispute record {
    string id;
    string merchantId;
    string? payoutId?;
    string subject;
    "open"|"resolved" status;
    string? resolutionNotes?;
    string createdAt;
};

public type Balance record {
    string merchantId;
    int amount;
    string currency;
};

public type ErrorUnauthorized record {|
    *http:Unauthorized;
    Error body;
|};
